# This is a basic workflow to help you get started with Actions

name: Compiple Latex

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_xelatex: true
          root_file: |
            main zh_cn.tex
            main en_us.tex
      - uses: actions/upload-artifact@v2
        with:
          name: zh_cn
          path: |
            src/main zh_cn.pdf  
            src/main en_us.pdf            
          if-no-files-found: error          

          