name: Compiple Latex

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_xelatex: true
          pre_compile: |
            cp -r ../fonts/* /usr/share/fonts/
            fc-cache -f
            fc-list :lang=zh-cn
          root_file: |
            main zh_cn.tex
            main en_us.tex
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: |
            src/main zh_cn.pdf  
            src/main en_us.pdf            
          if-no-files-found: error
